<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: BS2 - Win32 (WCE ARMV4I) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\Users\bami\AppData\Local\Temp\RSPB5DC.tmp" with contents
[
commctrl.lib coredll.lib winsock.lib Ws2.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"WinMainCRTStartup" /incremental:yes /pdb:"ARMV4IDbg/BS2.pdb" /debug /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib" /out:"ARMV4IDbg/BS2.exe" /subsystem:windowsce,4.00 /MACHINE:THUMB 
.\ARMV4IDbg\BS.obj
.\ARMV4IDbg\CESocket.obj
.\ARMV4IDbg\FRTT.obj
.\ARMV4IDbg\MyDB.obj
.\ARMV4IDbg\MyMain.obj
.\ARMV4IDbg\MYSTREAM.OBJ
.\ARMV4IDbg\MYSTRING.OBJ
]
Creating command line "link.exe @C:\Users\bami\AppData\Local\Temp\RSPB5DC.tmp"
<h3>Output Window</h3>
Linking...



<h3>Results</h3>
BS2.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
